default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DEV_DATABASE") { 'myproject_db' } %>
  username: <%= ENV.fetch("POSTGRES_DEV_USER") { 'myproject_user' } %>
  password: <%= ENV.fetch("POSTGRES_DEV_PASSWORD") { 'myproject_password' } %>
  host: <%= ENV.fetch("POSTGRES_DEV_HOST") { 'myproject_host' } %>
  port: <%= ENV.fetch("POSTGRES_DEV_PORT") { 'myproject_port' } %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_TEST_DATABASE") { 'myproject_db' } %>
  username: <%= ENV.fetch("POSTGRES_TEST_USER") { 'myproject_user' } %>
  password: <%= ENV.fetch("POSTGRES_TEST_PASSWORD") { 'myproject_password' } %>
  host: <%= ENV.fetch("POSTGRES_TEST_HOST") { 'myproject_host' } %>
  port: <%= ENV.fetch("POSTGRES_TEST_PORT") { 'myproject_port' } %>

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_PROD_DATABASE") { 'myproject_db' } %>
  username: <%= ENV.fetch("POSTGRES_PROD_USER") { 'myproject_user' } %>
  password: <%= ENV.fetch("POSTGRES_PROD_PASSWORD") { 'myproject_password' } %>
  host: <%= ENV.fetch("POSTGRES_PROD_HOST") { 'myproject_host' } %>
  port: <%= ENV.fetch("POSTGRES_PROD_PORT") { 'myproject_port' } %>
